### ISSUE TITLE
Error in  new(TimeSeriesObject)

### ISSUE THREAD

**Issue by jacquelyne-sun88** [Ylefol/TimeSeriesAnalysis#2] opened 2023-10-25 09:18 UTC
Hello Dr. Lefol,

I am trying to use my raw data from a RNA-seq experiment for the TimeSeries Analysis, and I have encountered this error and I can't seem to resolve it. 

raw_data="/~/TimeSeries/Trial1/Raw.txt"
meta_data="/~/TimeSeries/Trial1/Meta.csv"

TS_object <- new('TimeSeries_Object',group_names=c('Control','ETOH'),group_colors=graphic_vector,DE_method='DESeq2',DE_p_filter='padj',DE_p_thresh=0.05,DE_l2fc_thresh=1,PART_l2fc_thresh=4,sem_sim_org='org.Mm.eg.db',Gpro_org='mmusculus')
TS_object<-add_experiment_data(time_object=TS_object,sample_dta_path=meta_data,count_dta_path = raw_data)

The add_experiment_data created the error: 
Error in startsWith(final_counts$gene_id, "_") : non-character object(s)

I am not sure what is going wrong with this. I also don't see any examples that can use a textfile for the raw data as I usually do with DESeq2 and I am not sure if this will work. 

Thank you in advance!

**Comment by jacquelyne-sun88** [comment] 2023-10-25 09:20
Sorry - the traceback() generated the following response: 
6: startsWith(final_counts$gene_id, "_")
5: `[.data.frame`(final_counts, !startsWith(final_counts$gene_id, 
       "_"), )
4: final_counts[!startsWith(final_counts$gene_id, "_"), ]
3: prep_RNAseq_matrix(path_to_data, selected_samples)
2: create_raw_count_matrix(time_object = time_object, path_to_data = count_dta_path, 
       limma_id_replace = limma_ID_replace, samp_data = sample_data)
1: add_experiment_data(time_object = TS_object, sample_dta_path = meta_data, 
       count_dta_path = raw_data)

If any other information is needed to resolve this issue, please let me know. Thanks!

**Comment by Ylefol** [comment] 2023-10-25 10:30
Hello,

The reason for the error is that the function expects the path to a folder containing the count files (one file per sample).
However I have added a small condition to the problematic function where a text file should work in place of a folder. The condition for this is that the text file is tab delimited and contains the 'gene_id' header for the gene column, as well as column names which match the sample names given in the metadata file.

This solution has been pushed (as I'm writing this) so if you update/re-install the package it should work out.

Let me know if this worked or if another issue occurred, I'll be happy to help.

Yohan

**Comment by jacquelyne-sun88** [comment] 2023-10-25 16:09
Hi Yohan,

Thank you for your quick response. I have one more question – I ended up putting all the count files, one file per sample into a folder to run it, and it worked until I ran into another error. Does the package usually expect gene names rather than the ensembl id? I ran into another error below, and I noticed that the raw data provided is given in gene names rather than the IDs, and there is a function with limma to convert the IDs.

Error in Math.data.frame(list(`Hr0-1` = c("8365", "0", "178", "0", "0",  :
  non-numeric-alike variable(s) in data frame: Hr0-1, Hr0-2, Hr0-3, Hr0-4, Hr24-1, Hr24-2, Hr24-3, Hr24-4, Hr48-1, Hr48-2, Hr48-3, Hr48-4, Hr72-1, Hr72-2, Hr72-3, Hr72-4

Thank you!

Jacquelyne

From: Yohan Lefol ***@***.***>
Date: Wednesday, 25 October 2023 at 6:31 PM
To: Ylefol/TimeSeriesAnalysis ***@***.***>
Cc: SUN, Ka Li Jacquelyne ***@***.***>, State change ***@***.***>
Subject: Re: [Ylefol/TimeSeriesAnalysis] Error in new(TimeSeriesObject) (Issue #2)

Hello,

The reason for the error is that the function expects the path to a folder containing the count files (one file per sample).
However I have added a small condition to the problematic function where a text file should work in place of a folder. The condition for this is that the text file is tab delimited and contains the 'gene_id' header for the gene column, as well as column names which match the sample names given in the metadata file.

This solution has been pushed (as I'm writing this) so if you update/re-install the package it should work out.

Let me know if this worked or if another issue occurred, I'll be happy to help.

Yohan

**Comment by Ylefol** [comment] 2023-10-26 10:47
Hello,

Ensembl IDs should be fine. The reason I like to use gene names is simply for readability.
It appears that the error may be more on how the dataframe was build, though it is hard to say from this comment alone.
From the error you sent, it looks like the counts are actually loaded as strings due to the quotes around them.

What format are your individual files in? Are they txt or csv files?
If it is simpler for you, you could manually subset one of your files (for example, leave only the first 10 rows) and attach it to a comment. I could then take a look at what may be going wrong.

Best,
Yohan

**Comment by jacquelyne-sun88** [comment] 2023-10-26 10:52
Hello again, 

Sorry for all the questions, and thank you for your responses. My files are currently txt files in the raw data file, and the sample_file is in csv. 
<img width="215" alt="image" src="https://github.com/Ylefol/TimeSeriesAnalysis/assets/148952928/3eda37bb-f4de-4af1-945b-a861f9c700d7">
<img width="274" alt="image" src="https://github.com/Ylefol/TimeSeriesAnalysis/assets/148952928/aac46fd9-e4ca-4039-ad89-7bc37ebd581e">

Apologies, I'm quite new to bioinformatics and as I am doing a longitudinal experiment I wanted to see the temporal changes and found this package. Thank you for all your help!

**Comment by Ylefol** [comment] 2023-10-26 11:01
Hello,

No need to apologies, I'm happy that this pipeline is gaining attention and having people use it is a good way for me to better curate it towards user needs :)

In regards to the error, I believe the issue is that the individual text files contain headers (gene_id and Hr0_1).
Traditionally when we get count files they do not have these columns which is why we assume that these are not present when reading individual text files.

Essentially the pipeline is reading the first row as if it were a gene name and a count value, which is likely the cause of the above error.

Could you try to remove the first row from your individual text files and see if that works out?

Yohan

**Comment by jacquelyne-sun88** [comment] 2023-10-26 11:30
Hello, 

Is there any recommended RAM size specification? I am currently running this on a M1 Max with 64GB ram and it seems to exhaust my device memory and stopping the pipeline from running as well. I have removed the first line and it is seemingly still running into errors. I have a total of 16 files and it seems to get stuck every time. 

> TS_object <- new('TimeSeries_Object',group_names=c('Control','ETOH'),group_colors=graphic_vector,DE_method='DESeq2',DE_p_filter='padj',DE_p_thresh=0.05,DE_l2fc_thresh=1,PART_l2fc_thresh=4,sem_sim_org='org.Mm.eg.db',Gpro_org='mmusculus')
> TS_object<-add_experiment_data(time_object=TS_object,sample_dta_path=sample_data,count_dta_path = raw_data)

Error: vector memory exhausted (limit reached?)

Thank you again!
Jacquelyne

**Comment by Ylefol** [comment] 2023-10-26 12:35
Well at least we solved one error!

RAM should not be an issue (I've run larger sets of data on 32Gb of RAM) so there must be something else hindering the process.

If you're open to it, I get take a subset of the data and try running it on my end?
An alternative to this would be to set-up a meeting so that I can better understand the errors that are occurring.

In any case, it may be better to shift this conversation to work-related emails. I can then update this issue once the error and solution have been identified.

If this solution works for you, feel free to email me at yohanl@medisin.uio.no

Yohan

**Comment by 007gavin** [comment] 2023-11-22 16:41
Hello，
I have encountered an issue while using the add_experiment_data function and would appreciate your guidance in resolving it.

Issue Description:
When I attempt to use the add_experiment_data function with the following code:
> TS_object <- add_experiment_data(TS_object,sample_dta_path=my_path_sample_dta,count_dta_path=my_path_data)
I encounter the following error:
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'F:/0_R file/R_project/PBMC/series_matrix.txt/': Invalid argument
  Here is my data structure：
![image](https://github.com/Ylefol/TimeSeriesAnalysis/assets/97281235/e101587e-7d03-4c87-8568-2340a03f983d)
![image](https://github.com/Ylefol/TimeSeriesAnalysis/assets/97281235/5e5c9b7c-1366-4e70-b97a-a0f7ee936900)

**Comment by Ylefol** [comment] 2023-12-03 02:08
Hello,
Sorry for the late reply.

I am currently away from my office and Will be back (and able to look into this) at the beginning of January.

Kind regards,
Yohan.

**Comment by Ylefol** [comment] 2024-01-02 10:03
Hello again,

The error seems to indicate that R cannot find the file, however I see that the data format would also cause an issue. The pipeline expects the raw count format as DESeq2 also has this requirement.

If the error persists, or another one appears, feel free to either email me or open up another issue. However I will close this issue as we have solved the initial question for this issue.

For others that may have had a similar issue as the original post. The initial problem ended up being the data format itself, where there the control was also the first time point while the case (or experiment) was considered to be subsequent timepoint. TiSA could not be modified to accommodate this, however we wrote a series of alternate functions to handle this case. If you require these functions, or something similar, please feel free to email me.
I am choosing to not add them to the repository as they use is 'niche' and their inclusion is likely to clutter the repository.

Yohan

**Closed as completed by Ylefol** 2024-01-02 10:03 UTC
