### ISSUE TITLE
Pipeline use with non-model

### ISSUE THREAD

**Issue by jarcasariego** [Ylefol/TimeSeriesAnalysis#11] opened 2024-09-18 18:38 UTC
Hi, 
Is there a way to use the pipeline with a non-model organism? I noticed that running the pipeline requires a genome wide annotation database not available for my organism in this format. Is there a work around this for this issue? I tried to check if the ‘script_method’ was more accessible for modifications of this type, but could not find the folder in the repo
Thanks!
Javier

**Comment by Ylefol** [comment] 2024-09-19 06:48
Hello,

The first steps of the pipeline should be possible without a model organism. That is obtaining differential expressed genes and their clustering. However the gene ontology would require an annotated model. However I have not tested this myself. I plan on releasing a small fix to a few bugs later this week, I'll do a test of this as well and get back to you with the 'how to'.

I apologize for the absence of the script method, it appears I removed it and forgot to re-implement it. I'll add it to my upcoming fixes.

Best regards,
Yohan Lefol

**Comment by Ylefol** [comment] 2024-09-19 13:17
Hello,

I've re-introduced the script method. You will find this as a single R file in the extra_script folder.
I also ran a quick test to see if I could run the pipeline with no model organism. It is possible to get the DESeq2 results and PART results as explained above. 
From the script method, the changes to do are the following:
Two parameters of the object creation called 'sem_sim_org' and 'gpro_org' should be replaced with an empty string('').
Remove the 'add_semantic_similarity' function after the object creation.
Remove the gprofiler section and all sections after PART results.

Let me know if this works or if you encounter other issues.

Best,
Yohan

**Comment by jarcasariego** [comment] 2024-09-19 14:00
Hi Yohan, 
Thanks so much for the fast response and the work around. I'll give it a try right now. 
Best, 
Javier

**Comment by jarcasariego** [comment] 2024-09-19 14:11
Hi Yohan!
It worked fine. Both setting to organism info to an empty vector or keeping it as the wrong species (human in this case) results in the enrichment analysis to be skipped. The only thing that is failing on my end is the cluster heatmap (PART_heat.svg). I dont know why is not being created. The error I'm getting is at this section 
`par(mar = c(4, 4, .1, .1)) #set the parameters
knitr::include_graphics(paste0(name_result_folder,"PART_results/PART_heat.svg")) #plot the heatmap
plt_clust #Plot the cluster` 
`Error in knitr::include_graphics(paste0(name_result_folder, "PART_results/PART_heat.svg")) : 
  Cannot find the file(s): "../output/Adult_TS_output/PART_results/PART_heat.svg"`
Thanks for the help.
Cheers, 
Javier

**Comment by Ylefol** [comment] 2024-09-20 09:01
Hello,

This error usually pops up when a general issue occurs with the creation of the heatmap. The usual culprits are either low number of significant genes or an incorrect set-up of the sample data. Would it be possible to relay the number of significant genes sent to the 'compute PART' function (the variable is called signi_genes) as well as share the sample data for your experimental design ?

Best,
Yohan

**Comment by jarcasariego** [comment] 2024-09-20 14:02
Hi Yohan, 
I found what the problem was. The graphs are exported using svg() that requires cairo. However cairo doesnt work on mac installed R. I just changed the plot functions to png() and the problem was solved. Thanks for supporting this package. Very useful.
Best, 
Javier

**Comment by Ylefol** [comment] 2024-09-23 07:51
Hello,

Glad that you figured out the issue and thank you for letting me know. I didn't know SVGs would create issue with R based installations. I'll note down that SVGs should be the optional save method while making PNG the default.

Closing this issue for now, feel free to re-open it if needed.

Best,
Yohan

**Closed as completed by Ylefol** 2024-09-23 07:51 UTC

**Comment by jarcasariego** [comment] 2024-09-24 14:48
Thank you very much Yohan. I think the package is very useful. 
One last question, is there a way to run more than two groups with the pipeline?

Cheers, 

Javier

**Comment by Ylefol** [comment] 2024-09-25 07:46
Hello,

Unfortunately no. I considered this when developing it however it became too much of a headache and took away from the simplicity of the pipeline (which was the main goal).
The alternative I've used has been to create plots which combine the various runs of the pipeline. Something that I've done previously is create a version of the PART heatmap with all differential expression results from various runs of the pipeline. This can then be taken to illustrating cluster trajectories with multiple groups as well.

I have done this in the past, so if it is of interest I could dig up the script and add it to the 'extra_scripts' folder. I imagine it would take a day or two to clean it up and make sure it works as intended before adding it to the repository.

Best,
Yohan

**Comment by jarcasariego** [comment] 2024-09-25 15:26
Hi! 
Yes, that would be great. I was able to run the pipeline for each pairwise contrast and was looking at ways to integrate the clustering of all samples. If you have that code handy it will save me lots of time. I appreciate the help and no rush on this. I know this is an extraordinary request. 
Thanks!
Javier

**Comment by Ylefol** [comment] 2024-09-27 07:06
Hello,

I've found the script. It just needs a little bit of polishing.
I'll let you know here once it's in the repository. I'd expect it to be done by Monday/Tuesday.

Best,
Yohan

**Comment by Ylefol** [comment] 2024-09-30 11:17
Hello,

You will now be able to find the mentioned scripts in the 'extra_scripts' folder of this repository. I had to make some minor adjustments to already existing functions, so to run the script you will also need to update the pipeline to the latest version/push.

Best,
Yohan
